import type {
  Coordinate,
  Genre,
  Provider,
  SampleIdea,
  Technique,
} from './types';

// ============================================================
// 一、文学坐标（Literary Coordinate）
// 四层坐标体系，不包含纯爽文取向
// ============================================================

export const COORDINATES: Coordinate[] = [
  {
    id: 'premium-web',
    name: '精品网文取向',
    layer: '大众叙事层',
    coreLogic: '在可读性基础上追求世界观深度、人物弧光与思想表达',
    evaluation: '读者口碑、长线追读、IP 价值',
    representativeWorks: ['剑来', '诡秘之主', '庆余年', '将夜', '雪中悍刀行'],
    constraints: [
      '世界观必须有内在逻辑自洽性',
      '主角成长不仅是力量提升，更是认知与价值观的演变',
      '配角有独立动机和弧光，不是功能件',
      '允许慢热，但每章必须有信息增量或情感推进',
      '思想表达通过情节和人物自然流露，不靠说教',
      '金手指可以是隐喻性的，不必是系统面板',
      '爽感服务于叙事，不是叙事服务于爽感',
    ],
    namingStrategy:
      '名字有文化纹理和隐喻性；主角名可承载主题（如陈平安的「平安」二字）；配角名有辨识度但不功能化',
  },
  {
    id: 'historical-knowledge',
    name: '历史/知识叙事取向',
    layer: '历史与知识叙事层',
    coreLogic:
      '以扎实考据为基底，在历史缝隙中展开想象，兼顾智性乐趣与人文反思',
    evaluation: '历史还原度、智性密度、思想深度、叙事可读性',
    representativeWorks: [
      '长安十二时辰',
      '显微镜下的大明',
      '大医',
      '两京十五日',
      '食南之徒',
    ],
    constraints: [
      '历史背景须有考据支撑，细节可虚构但不可违背历史逻辑',
      '知识元素（制度、器物、风俗）须自然融入叙事，不炫学',
      '人物在历史洪流中的选择须有时代合理性',
      '对历史事件的态度是反思性的，不是简单歌颂或批判',
      '节奏可以紧凑，但智性密度必须保持',
      '允许对历史留白处进行合理想象，但须标记虚构边界',
      '历史人物的塑造须有立体性，不是标签化的善/恶',
    ],
    namingStrategy:
      '名字符合历史语境；可借用真实历史人物命名逻辑；虚构人物名不违和；名字可暗示人物的历史处境',
  },
  {
    id: 'speculative-depth',
    name: '思辨类型取向',
    layer: '类型文学深化层',
    coreLogic:
      '以类型（科幻/推理/悬疑/惊悚）为外壳，以思想实验和人性追问为内核',
    evaluation: '思想深度、逻辑严密性、人性洞察、类型的突破性',
    representativeWorks: [
      '三体',
      '球状闪电',
      '嫌疑人X的献身',
      '白夜行',
      '消失的爱人',
      '你一生的故事',
    ],
    constraints: [
      '类型设定（科幻设定/推理逻辑/悬疑结构）必须有内在严密性',
      '科学设定或推理链条不能有硬伤，细节须经得起推敲',
      '思想内核须涉及人性、文明、伦理、社会结构等深层命题',
      '推理的终点不是「谁是凶手」，而是「为什么人会这样做」',
      '科幻的终点不是技术奇观，而是「人在宇宙中的位置」',
      '类型元素服务于思想表达，不是思想为类型让路',
      '允许开放性或悲剧性结局，不强行圆满',
      '对读者的智性有尊重，不靠信息差制造廉价悬念',
    ],
    namingStrategy:
      '名字有符号性或隐喻性；科幻中名字可承载文明/物种特征；推理中名字可暗示人物关系或动机；整体不违和、不炫技',
  },
  {
    id: 'literary-fiction',
    name: '严肃文学取向',
    layer: '严肃文学层',
    coreLogic: '思想性与艺术性统一、时代概括、人物深度',
    evaluation: '茅盾文学奖评奖标准：思想内涵 + 艺术价值 + 中国气派',
    representativeWorks: [
      '平凡的世界',
      '白鹿原',
      '活着',
      '繁花',
      '一句顶一万句',
      '望春风',
    ],
    constraints: [
      '人物须有时代概括性',
      '叙事追求密实的生活细节流动',
      '题旨、人物、情节须在终点统一',
      '鼓励题材、主题、风格的多样化',
      '开放式或隐喻性结局优先',
      '语言本身是表达的一部分，不是透明容器',
      '叙事节奏可以缓慢，但每一处细节都应有存在的理由',
    ],
    namingStrategy:
      '日常化、普通但带隐喻性；名字承载人物的时代处境；多义性优先',
  },
];

// ============================================================
// 二、题材库（Genre）
// ============================================================

export const GENRES: Genre[] = [
  {
    id: 'mystery',
    name: '悬疑',
    group: '类型',
    themes: ['真相与谎言', '记忆的不可靠', '日常中的异常', '秘密的代价'],
    archetypes: ['追查者', '隐瞒者', '受害者', '知情旁观者'],
    namingStyle: '日常化名字，可暗示人物隐藏的秘密或处境',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'deduction',
    name: '推理',
    group: '类型',
    themes: ['逻辑与人性', '动机之谜', '正义的边界', '理性之恶'],
    archetypes: ['侦探', '镜像对手', '误导者', '沉默知情者'],
    namingStyle: '名字可暗示人物关系或动机，忌功能化标签',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'crime',
    name: '犯罪',
    group: '类型',
    themes: ['罪与罚', '制度与人', '底层生存逻辑', '恶的谱系'],
    archetypes: ['越界者', '执法者', '共谋者', '救赎者'],
    namingStyle: '写实、有地域与阶层质感',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'sci-fi-hard',
    name: '科幻·硬科幻',
    group: '科幻',
    themes: ['宇宙尺度的生存', '技术奇点', '文明的脆弱性', '物理规律的叙事化'],
    archetypes: ['科学家', '见证者', '决策者', '被技术异化者'],
    namingStyle: '名字可承载文明或物种特征，有符号性',
    coordinateAffinity: {
      'premium-web': '辅助',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'sci-fi-soft',
    name: '科幻·软科幻',
    group: '科幻',
    themes: ['技术伦理', '身份认同', '社会思想实验', '记忆的权力'],
    archetypes: ['实验对象', '体制内的怀疑者', '技术布道者', '觉醒者'],
    namingStyle: '近未来语感，普通名字与异化语境的反差',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'cyberpunk',
    name: '科幻·赛博朋克',
    group: '科幻',
    themes: ['高科技低生活', '身体与意识的边界', '资本垄断', '数字人格'],
    archetypes: ['边缘黑客', '企业特工', '改造人', 'AI 意识体'],
    namingStyle: '绰号与真名并行，代号承载身份裂痕',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'space-opera',
    name: '科幻·太空歌剧',
    group: '科幻',
    themes: ['文明冲突', '帝国兴衰', '个体与历史洪流', '星际尺度的伦理'],
    archetypes: ['舰队指挥官', '异族使者', '流亡者', '史官'],
    namingStyle: '多文明命名体系并存，名字体现文化谱系',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '罕见',
    },
  },
  {
    id: 'fantasy-epic',
    name: '奇幻·史诗',
    group: '奇幻',
    themes: ['命运与自由意志', '权力的腐蚀', '神话重述', '文明的轮回'],
    archetypes: ['悲剧英雄', '堕落贤者', '引路人', '献祭者'],
    namingStyle: '有文化纹理，命名体系与世界观语源一致',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '辅助',
      'speculative-depth': '偶尔',
      'literary-fiction': '罕见',
    },
  },
  {
    id: 'fantasy-urban',
    name: '奇幻·都市',
    group: '奇幻',
    themes: ['日常与异界的裂隙', '现代性批判', '隐匿的秩序'],
    archetypes: ['守门人', '双面生活者', '都市传说本体', '见习者'],
    namingStyle: '现代日常名与异界真名的张力',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '罕见',
      'speculative-depth': '常见',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'fantasy-dark',
    name: '奇幻·黑暗',
    group: '奇幻',
    themes: ['道德的灰色地带', '生存的代价', '信仰崩塌'],
    archetypes: ['反英雄', '背誓者', '殉道者', '投机者'],
    namingStyle: '粗粝、有伤口感的名字',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '辅助',
      'speculative-depth': '常见',
      'literary-fiction': '罕见',
    },
  },
  {
    id: 'romance-modern',
    name: '言情·现代',
    group: '言情',
    themes: ['亲密关系中的自我', '阶层与爱情', '创伤与治愈'],
    archetypes: ['回避型恋人', '救赎者', '镜像伴侣', '前任幽灵'],
    namingStyle: '当代语感，名字可暗含人物的情感模式',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '罕见',
      'speculative-depth': '偶尔',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'romance-historical',
    name: '言情·古代',
    group: '言情',
    themes: ['礼教与真心', '权力场中的情感', '身份错位'],
    archetypes: ['隐忍者', '破局者', '政治联姻者', '局外知情人'],
    namingStyle: '符合朝代命名习惯，闺名/表字可参与叙事',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '罕见',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'history',
    name: '历史',
    group: '历史',
    themes: ['大时代与小人物', '制度的运作逻辑', '历史的偶然与必然', '被遗忘者'],
    archetypes: ['小吏', '史官', '改革者', '末世守城人'],
    namingStyle: '严格符合时代命名逻辑，可借用真实历史人物谱系',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '罕见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'alt-history',
    name: '架空历史',
    group: '历史',
    themes: ['历史的或然性', '文明路径分岔', '蝴蝶效应'],
    archetypes: ['变革者', '旧秩序守护者', '穿越/先知者', '史家'],
    namingStyle: '贴近原型朝代又保持虚构辨识度',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '辅助',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'wuxia',
    name: '武侠',
    group: '东方幻想',
    themes: ['侠义与规矩', '师承与背叛', '江湖作为社会的倒影', '武与道的合一'],
    archetypes: ['浪子', '名门弃徒', '隐世高人', '反派宗师'],
    namingStyle: '名字有江湖气与留白感，绰号参与人物塑造',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '常见',
      'speculative-depth': '罕见',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'xianxia',
    name: '仙侠',
    group: '东方幻想',
    themes: ['长生与问道', '情与道的冲突', '秩序与反叛', '何为仙人'],
    archetypes: ['问道者', '堕仙', '守门人', '历劫者'],
    namingStyle: '道号与俗名并存，名字承载修行命题',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '辅助',
      'speculative-depth': '偶尔',
      'literary-fiction': '罕见',
    },
  },
  {
    id: 'horror',
    name: '恐怖',
    group: '类型',
    themes: ['未知的恐惧', '日常的崩塌', '集体禁忌', '恐惧作为隐喻'],
    archetypes: ['被诅咒者', '调查者', '禁忌触犯者', '幸存证人'],
    namingStyle: '平凡名字与异常境遇的反差',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '偶尔',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'thriller',
    name: '惊悚',
    group: '类型',
    themes: ['心理压迫', '信任的瓦解', '窥视与被窥视'],
    archetypes: ['操控者', '被困者', '不可靠的盟友', '双面人'],
    namingStyle: '日常化，制造安全感与危险的错位',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '偶尔',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'realistic-fiction',
    name: '现实虚构',
    group: '现实主义',
    themes: ['时代变迁中的普通人', '城乡裂变', '尊严与生计', '沉默的大多数'],
    archetypes: ['打工者', '返乡人', '留守者', '市井观察者'],
    namingStyle: '极度日常化，名字带时代印记',
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '常见',
      'speculative-depth': '罕见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'youth',
    name: '青春',
    group: '现实主义',
    themes: ['成长的阵痛', '自我认同', '懵懂与失去'],
    archetypes: ['敏感少年', '早慧者', '缺席的大人', '同龄镜像'],
    namingStyle: '校园语感，绰号与乳名的情感重量',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '罕见',
      'speculative-depth': '偶尔',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'workplace',
    name: '职场',
    group: '现实主义',
    themes: ['异化劳动', '权力微观结构', '专业主义的尊严'],
    archetypes: ['理想主义新人', '老练中层', '沉默的技术者', '制度化身'],
    namingStyle: '当代真实感，称谓（X总/X工）参与叙事',
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '罕见',
      'speculative-depth': '偶尔',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'dystopia',
    name: '反乌托邦',
    group: '思辨',
    themes: ['规训与反抗', '自由的代价', '幸福的暴政', '语言与思想控制'],
    archetypes: ['觉醒者', '体制信徒', '监察者', '地下网络'],
    namingStyle: '编号/去名化与真名的对抗',
    coordinateAffinity: {
      'premium-web': '辅助',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'apocalypse',
    name: '末世',
    group: '思辨',
    themes: ['文明崩塌后的人性', '秩序的重建', '幸存者的道德'],
    archetypes: ['幸存者领袖', '旧世界遗民', '掠夺者', '新秩序建立者'],
    namingStyle: '旧名作为文明遗物，新名作为生存宣言',
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'experimental',
    name: '实验文学',
    group: '实验',
    themes: ['形式即内容', '语言的边界', '观看方式的革命'],
    archetypes: ['叙述者自身', '碎片化的自我', '观察者'],
    namingStyle: '可匿名、符号化，命名本身成为实验',
    coordinateAffinity: {
      'premium-web': '罕见',
      'historical-knowledge': '罕见',
      'speculative-depth': '偶尔',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'metafiction',
    name: '元小说',
    group: '实验',
    themes: ['叙事的自我指涉', '作者与人物的权力关系', '虚构的伦理'],
    archetypes: ['作者化身', '觉醒的人物', '读者角色', '叙述者'],
    namingStyle: '名字可暴露虚构性，或与作者形成镜像',
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '罕见',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
];

// ============================================================
// 三、技法库（Technique）
// ============================================================

export const TECHNIQUE_CATEGORIES = [
  '叙事结构',
  '视角与叙述',
  '意识流技法',
  '叙事诡计',
  '情节方法',
  '风格参考',
  '思想表达',
] as const;

export const TECHNIQUES: Technique[] = [
  // ---- 叙事结构 ----
  {
    id: 'linear',
    name: '线性结构',
    category: '叙事结构',
    description: '按时间顺序推进，依靠因果链积累张力',
    useCase: '人物弧光完整、时代跨度大的故事',
    combination: ['伏笔与回收', '考据笔法'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '辅助',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'flashback',
    name: '倒叙结构',
    category: '叙事结构',
    description: '从结局或高潮后开场，回追事件成因',
    useCase: '以「为什么会走到这一步」为核心悬念的故事',
    combination: ['不可靠叙述', '伏笔与回收'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'frame',
    name: '框架式结构',
    category: '叙事结构',
    description: '外层叙事包裹内层故事，讲述行为本身参与意义生成',
    useCase: '需要「谁来讲、为何讲」成为主题一部分的故事',
    combination: ['不可靠叙述', '隐喻性结构'],
    coordinateAffinity: {
      'premium-web': '辅助',
      'historical-knowledge': '常见',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'radial',
    name: '放射式结构',
    category: '叙事结构',
    description: '一个核心事件，多个视角或线索由其向外辐射',
    useCase: '群像、罗生门式真相拼合',
    combination: ['多重视角轮换', '主题复调'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'labyrinth',
    name: '迷宫式结构',
    category: '叙事结构',
    description: '叙事路径故意缠绕、回环，读者与人物一同迷失',
    useCase: '认知困境、身份迷宫类题材',
    combination: ['非线性时间', '不可靠叙述'],
    coordinateAffinity: {
      'premium-web': '罕见',
      'historical-knowledge': '偶尔',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'parallel',
    name: '并列式结构',
    category: '叙事结构',
    description: '多条故事线并行展开，靠主题而非因果关联',
    useCase: '时代群像、主题复调型作品',
    combination: ['多线并行', '主题复调'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'dual-converge',
    name: '双线交汇',
    category: '叙事结构',
    description: '两条线独立推进，在关键节点汇合，意义在交汇处爆发',
    useCase: '过去/现在、追凶/逃亡、两代人命运对照',
    combination: ['伏笔与回收', '反转'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'ring',
    name: '环形结构',
    category: '叙事结构',
    description: '结尾回到开头，但意义已被全程改写',
    useCase: '命运轮回、创伤重现、主题反讽',
    combination: ['隐喻性结构', '时间循环'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  // ---- 视角与叙述 ----
  {
    id: 'first-person-limited',
    name: '第一人称有限视角',
    category: '视角与叙述',
    description: '读者被锁死在「我」的感官与认知边界内',
    useCase: '心理浓度高、悬念依赖认知差的故事',
    combination: ['内心独白', '不可靠叙述'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '辅助',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'unreliable-narrator',
    name: '不可靠叙述',
    category: '视角与叙述',
    description: '叙述者的讲述与事实存在裂缝，裂缝本身就是主题',
    useCase: '自欺、记忆扭曲、叙事自我辩护',
    combination: ['叙述者诡计', '心理时间'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'multi-pov',
    name: '多重视角轮换',
    category: '视角与叙述',
    description: '多个人物轮流担任视角中心，同一事件被多次赋义',
    useCase: '群像、战争、家族、多立场议题',
    combination: ['放射式结构', '主题复调'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'second-person',
    name: '第二人称实验',
    category: '视角与叙述',
    description: '以「你」行文，制造代入、指控或催眠感',
    useCase: '实验性章节、读者共谋型叙事',
    combination: ['内心独白', '迷宫式结构'],
    coordinateAffinity: {
      'premium-web': '罕见',
      'historical-knowledge': '罕见',
      'speculative-depth': '偶尔',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'omniscient',
    name: '全知旁观',
    category: '视角与叙述',
    description: '叙述者俯瞰全局，可介入评论，保持克制的距离感',
    useCase: '史诗、家族编年、时代画卷',
    combination: ['线性结构', '考据笔法'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '辅助',
      'literary-fiction': '常见',
    },
  },
  // ---- 意识流技法 ----
  {
    id: 'interior-monologue',
    name: '内心独白',
    category: '意识流技法',
    description: '直接呈现人物未加修饰的思维流',
    useCase: '高心理密度的关键场景',
    combination: ['第一人称有限视角', '感官印象'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '偶尔',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'free-association',
    name: '自由联想',
    category: '意识流技法',
    description: '思维由一个感官刺激跳跃到记忆与想象的深处',
    useCase: '创伤触发、记忆闪回、物象抒情',
    combination: ['心理时间', '感官印象'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '罕见',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'sensory-impression',
    name: '感官印象',
    category: '意识流技法',
    description: '以嗅觉、触觉、温度等非视觉感官锚定场景',
    useCase: '氛围营造、记忆的身体性',
    combination: ['自由联想', '抒情'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'psychological-time',
    name: '心理时间',
    category: '意识流技法',
    description: '叙事时间跟随心理体验伸缩，一秒可成一章，十年可成一段',
    useCase: '创伤、顿悟、濒死体验、重大抉择瞬间',
    combination: ['内心独白', '非线性时间'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '罕见',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'montage',
    name: '蒙太奇',
    category: '意识流技法',
    description: '碎片场景的快速组接，靠并置产生意义',
    useCase: '时代变迁压缩、多人物同步状态',
    combination: ['多线并行', '感官印象'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'indirect-interior',
    name: '间接内心独白',
    category: '意识流技法',
    description: '第三人称外壳包裹第一人称心理，叙述者与人物声音交融',
    useCase: '需要保持叙事距离又深入心理的场景',
    combination: ['全知旁观', '心理时间'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  // ---- 叙事诡计 ----
  {
    id: 'trick-point',
    name: '点式诡计',
    category: '叙事诡计',
    description: '单一关键信息的隐瞒或误导，揭晓时全局翻转',
    useCase: '本格推理、核心悬念',
    combination: ['伏笔与回收', '反转'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'trick-plane',
    name: '面式诡计',
    category: '叙事诡计',
    description: '系统性铺设误导网络，多处细节共同支撑一个假相',
    useCase: '长线悬疑、世界观级反转',
    combination: ['多重视角轮换', '伏笔与回收'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'trick-word',
    name: '文字诡计',
    category: '叙事诡计',
    description: '利用称谓、性别、时间的语言模糊性误导读者',
    useCase: '叙诡推理、身份错位',
    combination: ['叙述者诡计', '点式诡计'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '偶尔',
      'speculative-depth': '核心',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'trick-structure',
    name: '结构诡计',
    category: '叙事诡计',
    description: '章节顺序、时间线编排本身就是骗局',
    useCase: '双线叙诡、时间错位型悬疑',
    combination: ['双线交汇', '非线性时间'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '偶尔',
      'speculative-depth': '核心',
      'literary-fiction': '常见',
    },
  },
  {
    id: 'trick-narrator',
    name: '叙述者诡计',
    category: '叙事诡计',
    description: '叙述者本人就是最大的谎言源',
    useCase: '心理悬疑、自我欺骗主题',
    combination: ['不可靠叙述', '文字诡计'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '偶尔',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  // ---- 情节方法 ----
  {
    id: 'foreshadowing',
    name: '伏笔与回收',
    category: '情节方法',
    description: '早期埋设的细节在后期获得意义回响',
    useCase: '一切重视「重读价值」的作品',
    combination: ['隐喻性结构', '反转'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'reversal',
    name: '反转',
    category: '情节方法',
    description: '颠覆读者对人物、动机或真相的既有判断',
    useCase: '悬疑收束、价值观翻转时刻',
    combination: ['伏笔与回收', '点式诡计'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'misunderstanding',
    name: '误会与巧合',
    category: '情节方法',
    description: '人物基于错误信息行动，命运因错位而改变',
    useCase: '命运悲剧、黑色幽默、世情小说',
    combination: ['双线交汇', '荒诞'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '常见',
      'speculative-depth': '辅助',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'doppelganger',
    name: '双生/替身',
    category: '情节方法',
    description: '两个人物互为镜像，身份、命运或道德彼此映照',
    useCase: '身份主题、自我分裂、镜像对手',
    combination: ['隐喻性结构', '不可靠叙述'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '偶尔',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'time-loop',
    name: '时间循环',
    category: '情节方法',
    description: '人物困于重复的时间，每次循环推进认知或暴露真相',
    useCase: '命运、救赎、存在主义命题',
    combination: ['环形结构', '心理时间'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '偶尔',
    },
  },
  {
    id: 'multi-thread',
    name: '多线并行',
    category: '情节方法',
    description: '多条情节线独立推进、相互映照，终局收束',
    useCase: '群像史诗、社会全景',
    combination: ['并列式结构', '蒙太奇'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  // ---- 风格参考 ----
  {
    id: 'cold',
    name: '冷峻',
    category: '风格参考',
    description: '克制、零度的叙述语调，让事实自身产生寒意',
    useCase: '犯罪、战争、创伤叙事',
    combination: ['极简', '全知旁观'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'lyrical',
    name: '抒情',
    category: '风格参考',
    description: '情感浓度高的语言，物象皆带主观色彩',
    useCase: '青春、怀旧、挽歌式叙事',
    combination: ['感官印象', '诗性'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '偶尔',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'absurd',
    name: '荒诞',
    category: '风格参考',
    description: '以夸张变形的情境照出现实的非理性',
    useCase: '体制批判、存在主义喜剧',
    combination: ['黑色幽默', '隐喻性结构'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '偶尔',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'dark-humor',
    name: '黑色幽默',
    category: '风格参考',
    description: '在绝望处发笑，笑比哭更冷',
    useCase: '战争、犯罪、底层叙事',
    combination: ['荒诞', '冷峻'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'poetic',
    name: '诗性',
    category: '风格参考',
    description: '语言追求韵律与意象密度，叙事让位于审美体验',
    useCase: '片段式叙事、意象主导的章节',
    combination: ['抒情', '感官印象'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '常见',
      'speculative-depth': '偶尔',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'minimal',
    name: '极简',
    category: '风格参考',
    description: '删繁就简，留白处皆是意义',
    useCase: '克制型情感叙事、短篇',
    combination: ['冷峻', '隐喻性结构'],
    coordinateAffinity: {
      'premium-web': '辅助',
      'historical-knowledge': '偶尔',
      'speculative-depth': '常见',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'archival',
    name: '考据笔法',
    category: '风格参考',
    description: '以制度、器物、风俗的精确细节构建可信世界',
    useCase: '历史、行业文、知识叙事',
    combination: ['全知旁观', '感官印象'],
    coordinateAffinity: {
      'premium-web': '辅助',
      'historical-knowledge': '核心',
      'speculative-depth': '辅助',
      'literary-fiction': '辅助',
    },
  },
  {
    id: 'intellectual-dialogue',
    name: '智性对白',
    category: '风格参考',
    description: '对白承载思想交锋，言语即行动',
    useCase: '价值观对立的对手戏、审讯、论辩',
    combination: ['哲学对话', '伦理困境设计'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  // ---- 思想表达 ----
  {
    id: 'metaphor-structure',
    name: '隐喻性结构',
    category: '思想表达',
    description: '整体故事结构本身就是一个大隐喻，情节层与寓意层并行',
    useCase: '一切追求「故事即思想」的作品',
    combination: ['伏笔与回收', '主题复调'],
    coordinateAffinity: {
      'premium-web': '核心',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'thematic-polyphony',
    name: '主题复调',
    category: '思想表达',
    description: '多个人物/线索各自演绎同一主题的不同声部',
    useCase: '群像、多立场议题、价值观辩论型作品',
    combination: ['多重视角轮换', '并列式结构'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'philosophical-dialogue',
    name: '哲学对话',
    category: '思想表达',
    description: '人物对话进入哲学层面，但由具体处境驱动，不说教',
    useCase: '对手戏、临终、抉择时刻',
    combination: ['智性对白', '伦理困境设计'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '常见',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'ethical-dilemma',
    name: '伦理困境设计',
    category: '思想表达',
    description: '让人物在「没有正确答案」的两难中暴露其价值排序',
    useCase: '主题深化的核心场景、高潮设计',
    combination: ['哲学对话', '人物弧光'],
    coordinateAffinity: {
      'premium-web': '常见',
      'historical-knowledge': '核心',
      'speculative-depth': '核心',
      'literary-fiction': '核心',
    },
  },
  {
    id: 'civilization-scale',
    name: '文明尺度叙事',
    category: '思想表达',
    description: '将个体命运放置在文明、物种、宇宙时间尺度上衡量',
    useCase: '科幻、史诗、历史终局',
    combination: ['全知旁观', '隐喻性结构'],
    coordinateAffinity: {
      'premium-web': '偶尔',
      'historical-knowledge': '罕见',
      'speculative-depth': '核心',
      'literary-fiction': '辅助',
    },
  },
];

// ============================================================
// 四、模型提供商（BYOK）
// ============================================================

export const PROVIDERS: Provider[] = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    models: ['deepseek-flash', 'deepseek-chat', 'deepseek-reasoner'],
    supportsVision: true,
    docsUrl: 'https://platform.deepseek.com',
  },
  {
    id: 'moonshot',
    name: 'Kimi (Moonshot)',
    baseUrl: 'https://api.moonshot.cn/v1',
    models: ['kimi-k3', 'moonshot-v1-128k'],
    supportsVision: true,
    docsUrl: 'https://platform.moonshot.cn',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4o', 'gpt-4o-mini'],
    supportsVision: true,
    docsUrl: 'https://platform.openai.com',
  },
  {
    id: 'custom',
    name: '自定义 (OpenAI 兼容)',
    baseUrl: '',
    models: [],
    supportsVision: true,
    docsUrl: '',
  },
];

// ============================================================
// 五、预置示例构想
// ============================================================

export const SAMPLE_IDEAS: SampleIdea[] = [
  {
    label: '思辨科幻示例',
    coordinate: 'speculative-depth',
    genres: ['sci-fi-soft', 'dystopia'],
    idea:
      '近未来，政府推出「记忆公证」服务：重大承诺签署时，双方的记忆会被提取并存档，违约时记忆可作为法庭证据。一名记忆公证员在整理一桩违约案时，发现自己十年前的一段记忆也被存档过——但他完全不记得签署过任何承诺。他开始追查，逐渐意识到自己的某段人生可能被合法地「删除」了。',
  },
  {
    label: '历史知识示例',
    coordinate: 'historical-knowledge',
    genres: ['history', 'mystery'],
    idea:
      '明朝万历年间，一名负责管理皇历的钦天监小吏发现，连续三年冬至的观测记录被人篡改过。篡改不是为了伪造祥瑞，而是为了掩盖一次真实的异常天象。他想查清真相，却发现牵涉到历法之争背后的朝廷党争、西洋传教士的处境，以及一个即将被从历史中抹去的真相。',
  },
  {
    label: '严肃文学示例',
    coordinate: 'literary-fiction',
    genres: ['realistic-fiction', 'youth'],
    idea:
      '县城中学的语文老师年轻时写过一部长篇小说，被退稿十七次后把稿子烧了，从此安心教书。二十年后，他当年的一个学生在省城旧书店发现了一册油印的、署名是他笔名的残稿——原来当年有人偷偷印过五十册。学生带着残稿回到县城，发现老师已经中风失语。',
  },
];

// ============================================================
// 便捷查询函数
// ============================================================

export function getCoordinate(id: string): Coordinate | undefined {
  return COORDINATES.find((c) => c.id === id);
}

export function getGenre(id: string): Genre | undefined {
  return GENRES.find((g) => g.id === id);
}
